name: /projects/bfwt/hahsan/sae_env
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=20_gnu
  - bzip2=1.0.8=h4777abc_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - icu=78.2=hb1525cb_0
  - ld_impl_linux-aarch64=2.45.1=default_h1979696_101
  - libexpat=2.7.3=hfae3067_0
  - libffi=3.5.2=h376a255_0
  - libgcc=15.2.0=h8acb6b2_17
  - libgcc-ng=15.2.0=he9431aa_17
  - libgomp=15.2.0=h8acb6b2_17
  - liblzma=5.8.2=he30d5cf_0
  - libnsl=2.0.1=h86ecc28_1
  - libsqlite=3.51.2=h10b116e_0
  - libstdcxx=15.2.0=hef695bb_17
  - libuuid=2.41.3=h1022ec0_0
  - libxcrypt=4.4.36=h31becfc_1
  - libzlib=1.3.1=h86ecc28_2
  - ncurses=6.5=ha32ae93_3
  - openssl=3.6.1=h546c87b_1
  - packaging=26.0=pyhcf101f3_0
  - pip=26.0.1=pyh8b19718_0
  - python=3.10.19=h28be5d3_3_cpython
  - readline=8.3=hb682ff5_0
  - tk=8.6.13=noxft_h0dc03b3_103
  - wheel=0.46.3=pyhd8ed1ab_0
  - zstd=1.5.7=h85ac4a6_6
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - automated-interpretability==0.0.23
      - babe==0.0.7
      - beartype==0.14.1
      - better-abc==0.0.3
      - bidict==0.23.1
      - bitsandbytes==0.49.2
      - blobfile==2.1.1
      - boostedblob==0.15.6
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - circuitsvis==1.43.3
      - click==8.3.1
      - config2py==0.1.46
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==2.21.0
      - dictionary-learning==0.1.0
      - diffusers==0.36.0
      - dill==0.3.8
      - docstring-parser==0.17.0
      - dol==0.3.38
      - einops==0.8.2
      - exceptiongroup==1.3.1
      - fancy-einsum==0.0.3
      - filelock==3.21.2
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - gprof2dot==2025.4.14
      - graze==0.1.39
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.2
      - i2==0.1.63
      - idna==3.11
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - iniconfig==2.3.0
      - jaxtyping==0.3.7
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - llvmlite==0.46.0
      - lxml==4.9.4
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.1
      - multiprocess==0.70.16
      - narwhals==2.16.0
      - networkx==3.4.2
      - nltk==3.9.2
      - nnsight==0.3.7
      - numba==0.63.1
      - numpy==1.26.4
      - orjson==3.11.7
      - pandas==2.3.3
      - patsy==1.0.2
      - pillow==12.1.1
      - platformdirs==4.7.0
      - plotly==5.24.1
      - plotly-express==0.4.1
      - pluggy==1.6.0
      - propcache==0.4.1
      - protobuf==6.33.5
      - psutil==7.2.2
      - py2store==0.1.22
      - pyarrow==23.0.0
      - pycryptodomex==3.23.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pynndescent==0.6.0
      - pyparsing==3.3.2
      - pytest==9.0.2
      - pytest-profiling==1.8.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-engineio==4.13.1
      - python-socketio==5.16.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==26.0.0
      - regex==2026.1.15
      - requests==2.32.5
      - rich==14.3.2
      - sae-lens==5.10.7
      - safetensors==0.4.5
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.52.0
      - setuptools==65.5.0
      - shellingham==1.5.4
      - simple-parsing==0.1.8
      - simple-websocket==1.1.0
      - six==1.17.0
      - smmap==5.0.2
      - statsmodels==0.14.6
      - sympy==1.13.1
      - tenacity==9.1.4
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.2
      - tomli==2.4.0
      - torch==2.6.0+cu126
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.3
      - traitlets==5.14.3
      - transformer-lens==2.17.0
      - transformers==4.57.6
      - transformers-stream-generator==0.0.5
      - typeguard==4.5.0
      - typer==0.23.1
      - typer-slim==0.23.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - umap-learn==0.5.11
      - urllib3==2.6.3
      - uvloop==0.22.1
      - wadler-lindig==0.1.7
      - wandb==0.25.0
      - websocket-client==1.9.0
      - wsproto==1.3.2
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.22.0
prefix: /projects/bfwt/hahsan/sae_env
